//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falando_de_web.Models.Entidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anexo
    {
        public int Codigo { get; set; }
        public int Post { get; set; }
        public string Titulo { get; set; }
        public string Link { get; set; }
    
        public virtual Post Post1 { get; set; }
    }
}
