//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falando_de_web.Models.Entidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class Erro
    {
        public int Codigo { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public string Mensagem { get; set; }
        public string InnerException { get; set; }
        public string Navegador { get; set; }
        public string URL { get; set; }
        public string IP { get; set; }
    }
}
