//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falando_de_web.Models.Entidade
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Conexao : DbContext
    {
        public Conexao()
            : base("name=Conexao")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categoria> Categoria { get; set; }
        public DbSet<Contato> Contato { get; set; }
        public DbSet<Erro> Erro { get; set; }
        public DbSet<Log> Log { get; set; }
        public DbSet<Post> Post { get; set; }
        public DbSet<Texto> Texto { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Anexo> Anexo { get; set; }
    }
}
