//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falando_de_web.Models.Entidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Anexo = new HashSet<Anexo>();
        }
    
        public int Codigo { get; set; }
        public int Categoria { get; set; }
        public int Usuario { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public System.DateTime DataPublicacao { get; set; }
        public string Titulo { get; set; }
        public string Subtitulo { get; set; }
        public string Previa { get; set; }
        public string Texto { get; set; }
        public string Tag { get; set; }
        public string Fonte { get; set; }
        public bool Aprovado { get; set; }
    
        public virtual Categoria Categoria1 { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<Anexo> Anexo { get; set; }
    }
}
